# sudo false for using new container-based infrastructure,
# see https://docs.travis-ci.com/user/migrating-from-legacy/
# Note: Apparently doesn't work in combination with .NET Core yet.
# Opened https://github.com/travis-ci/travis-ci/issues/8216
# Uncommented for now to make sure nothing suddenly breaks when they enable it.
#sudo: false
git:
  depth: 1

# language, mono, dotnet, dist are all necessary for .NET Core,
# see https://docs.travis-ci.com/user/languages/csharp/#.NET-Core
language: csharp
mono: none
dotnet: 1.0.1
dist: trusty

script:
 - scripts/build.sh
 