version: 1.0.0.{build}
clone_depth: 1
install:
- ps: choco upgrade chocolatey -y
build_script:
- ps: scripts\build.ps1
test: off
artifacts:
- path: artifacts\*.zip
- path: artifacts\*.nupkg
deploy:
- provider: GitHub
  auth_token:
    secure: Pr/IscMk66i5SHGCCLZTMkou4PNoH3+E6yj2HwsFdyR7wBNozDwpZws5BRZUgpPVMR12oPNerx5692x6WVnraXH9PJROK4oOpSUOGYr+e9o=
  on:
    branch: master
- provider: NuGet
  server: https://www.myget.org/F/hello-netcoreapp/
  api_key:
    secure: pFtnAlh5glfIoI7Mn9U7ayhClcGFVpp8yauJ/Y3b2F/U4egDUAl51kpQFT12gGr9kTfKzWV9PZ7s8mCT7YliuEvkSvcmu5p/ckNZWD265oQ=
  on:
    branch: master
